package com.example.ivory.ui.theme.screen.main.home

import androidx.compose.foundation.background
import androidx.compose.foundation.layout.Arrangement
import androidx.compose.foundation.layout.Column
import androidx.compose.foundation.layout.Spacer
import androidx.compose.foundation.layout.fillMaxSize
import androidx.compose.foundation.layout.fillMaxWidth
import androidx.compose.foundation.layout.height
import androidx.compose.foundation.layout.padding
import androidx.compose.foundation.shape.RoundedCornerShape
import androidx.compose.material.icons.Icons
import androidx.compose.material.icons.outlined.WarningAmber
import androidx.compose.material3.Button
import androidx.compose.material3.ButtonDefaults
import androidx.compose.material3.Card
import androidx.compose.material3.CardDefaults
import androidx.compose.material3.Icon
import androidx.compose.material3.Text
import androidx.compose.runtime.Composable
import androidx.compose.ui.Alignment
import androidx.compose.ui.Modifier
import androidx.compose.ui.graphics.Color
import androidx.compose.ui.text.font.FontWeight
import androidx.compose.ui.text.style.TextAlign
import androidx.compose.ui.unit.dp
import androidx.compose.ui.unit.sp
import androidx.hilt.lifecycle.viewmodel.compose.hiltViewModel
import com.example.ivory.domain.model.Post
import com.example.ivory.viewModels.main.ContentWarningViewModel

@Composable
fun ContentWarningScreen(
    postId: String,
    onShowContent: (String) -> Unit,
    onBack: () -> Unit,
    viewModel: ContentWarningViewModel = hiltViewModel()
) {
    val post = viewModel.findPost(postId)
    if (post == null) {
        MissingPostScreen(onBack)
    } else {
        WarningContent(post, onShowContent, onBack)
    }
}

@Composable
private fun WarningContent(post: Post, onShowContent: (String) -> Unit, onBack: () -> Unit) {
    Column(
        modifier = Modifier.fillMaxSize().background(Color(0xFF0F0F0F)).padding(20.dp),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Card(
            shape = RoundedCornerShape(24.dp),
            colors = CardDefaults.cardColors(containerColor = Color(0xFF1D1B24)),
            modifier = Modifier.fillMaxWidth()
        ) {
            Column(
                modifier = Modifier.padding(24.dp),
                horizontalAlignment = Alignment.CenterHorizontally
            ) {
                Icon(Icons.Outlined.WarningAmber, null, tint = Color(0xFFFF5B68))
                Spacer(Modifier.height(10.dp))
                Text("CONTENT WARNING", color = Color(0xFFFF8A93), fontWeight = FontWeight.Bold, fontSize = 13.sp)
                Spacer(Modifier.height(12.dp))
                Text(
                    "You are about to view content our system flagged as toxic.",
                    color = Color.White,
                    fontSize = 23.sp,
                    fontWeight = FontWeight.ExtraBold,
                    textAlign = TextAlign.Center
                )
                Spacer(Modifier.height(12.dp))
                Text(
                    post.moderation.reason ?: "This post may contain harmful, abusive, or disturbing language.",
                    color = Color.LightGray,
                    textAlign = TextAlign.Center,
                    fontSize = 14.sp
                )
                Spacer(Modifier.height(20.dp))
                Text("BEFORE YOU CONTINUE", color = Color.White, fontWeight = FontWeight.Bold)
                Spacer(Modifier.height(8.dp))
                Text(
                    "• This content was hidden for your protection.\n" +
                        "• The warning is generated by automated analysis and may not be perfect.\n" +
                        "• Revealing it is your choice and responsibility.\n" +
                        "• Viewing does not mean Ivory endorses the content.",
                    color = Color.LightGray,
                    fontSize = 13.sp,
                    lineHeight = 19.sp
                )
                Spacer(Modifier.height(20.dp))
                Text("Think before you reveal", color = Color(0xFFFF8A93), fontWeight = FontWeight.Bold)
                Text("You do not need to see this post. You can go back and continue scrolling.", color = Color.Gray, fontSize = 13.sp, textAlign = TextAlign.Center)
                Spacer(Modifier.height(20.dp))
                Button(
                    onClick = { onShowContent(post.id) },
                    modifier = Modifier.fillMaxWidth(),
                    shape = RoundedCornerShape(16.dp),
                    colors = ButtonDefaults.buttonColors(containerColor = Color(0xFFFF5263))
                ) { Text("SHOW CONTENT") }
                Spacer(Modifier.height(8.dp))
                Button(
                    onClick = onBack,
                    modifier = Modifier.fillMaxWidth(),
                    colors = ButtonDefaults.buttonColors(containerColor = Color.Transparent, contentColor = Color.LightGray)
                ) { Text("Go back") }
            }
        }
    }
}

@Composable
fun RevealedContentScreen(
    postId: String,
    onBack: () -> Unit,
    viewModel: ContentWarningViewModel = hiltViewModel()
) {
    val post = viewModel.findPost(postId)
    if (post == null) {
        MissingPostScreen(onBack)
        return
    }
    Column(
        modifier = Modifier.fillMaxSize().background(Color(0xFF0F0F0F)).padding(20.dp),
        verticalArrangement = Arrangement.Center
    ) {
        Text("Revealed content", color = Color.White, fontWeight = FontWeight.ExtraBold, fontSize = 24.sp)
        Spacer(Modifier.height(12.dp))
        Card(colors = CardDefaults.cardColors(containerColor = Color(0xFF1A1A1A)), shape = RoundedCornerShape(18.dp)) {
            Column(Modifier.padding(18.dp)) {
                Text(post.username, color = Color(0xFFB6AAFF), fontWeight = FontWeight.Bold)
                Spacer(Modifier.height(10.dp))
                Text(post.content, color = Color.White, fontSize = 16.sp)
            }
        }
        Spacer(Modifier.height(20.dp))
        Button(onClick = onBack, modifier = Modifier.fillMaxWidth(), colors = ButtonDefaults.buttonColors(containerColor = Color(0xFF6C4DFF))) {
            Text("Back to Home")
        }
    }
}

@Composable
private fun MissingPostScreen(onBack: () -> Unit) {
    Column(
        modifier = Modifier.fillMaxSize().background(Color(0xFF0F0F0F)).padding(20.dp),
        verticalArrangement = Arrangement.Center,
        horizontalAlignment = Alignment.CenterHorizontally
    ) {
        Text("This post is no longer available.", color = Color.White)
        Spacer(Modifier.height(12.dp))
        Button(onClick = onBack) { Text("Back to Home") }
    }
}
